pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "fabric-server-mods"

include "mouse-boat-steering"
include "server-latency-display"
